### ISSUE TITLE
Communication - Jimmy

### ISSUE THREAD

**Issue by sowmya1408** [RailsGirlsCPH/mentor-mentee-platform#101] opened 2019-06-25 17:37 UTC
I can choose here many mentees I can handle so that I don't end if overwhelmed.
I would like to write a short bio about me so people can understand me a bit.
I want to choose from a list of categories of what I can offer help in.A paragraph would explain each options/from what I can select.I can also add to that list.
While registration, if they need help with there bio, may be can have examples of stories and also some words they want to put on.
I want to write what projects I work/Git with so mentees can find me.

**Comment by diwanow** [comment] 2019-11-02 20:26
> 1. I can choose here many mentees I can handle so that I don't end if overwhelmed.

Duplicate of #80

> 2. I would like to write a short bio about me so people can understand me a bit.

Almost duplicate of #105. #105 is vague enough, so we will have a discussion about both Jimmy and Olivia and decide on further details.

> 3. I want to choose from a list of categories of what I can offer help in.A paragraph would explain each options/from what I can select.I can also add to that list.

#89 #112 #121 #122 all mention something in that direction

> 4. While registration, if they need help with there bio, may be can have examples of stories and also some words they want to put on.

Added to #105

> 5. I want to write what projects I work/Git with so mentees can find me.

Added to #105

The fact that all these scenarios were captured by another group too only shows they are important. Thanks for taking the time to file it!
I am closing this story to reduce the number of similar issues we have.

**Closed by diwanow** 2019-11-02 20:26 UTC
Labels: story writing workshop
