### ISSUE TITLE
Search Box (Story Writing workshop) 25-06-19

### ISSUE THREAD

**Issue by rakhshanda-rashid** [RailsGirlsCPH/mentor-mentee-platform#102] opened 2019-06-25 17:37 UTC
As a mentor jimmy  want to give back to the society who help him to make his career, But with the same time he want to learn more with others. So he want when he will search on search box a specific skill the list of mentors and mentee would appear so he can join with them and share his skills and learn from them at the same time.

**Comment by diwanow** [comment] 2019-11-02 20:27
Duplicate of #81 #89 

Thanks for writing this! Having this duplicate only means it was good since another group also came to the same ideas i.e. it is needed

**Closed by diwanow** 2019-11-02 20:27 UTC
Labels: story writing workshop
